import type { Metadata } from "next";
import { Geist, Geist_Mono, Mandali } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext"; // Importa el contexto
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/site.webmanifest",
  keywords: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
  themeColor: "dark",
  authors: [
    {
      name: "Jorge Videz",
      url: "https://tu-sitio-web.com",
    },
  ],
  viewport: "width=device-width, initial-scale=1",
  icons: [
    { rel: "icon", url: "icons/Logoinventariobovino-512.png" },
    { rel: "apple-touch-icon", url: "icons/Logoinventariobovino-192.png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head>
        <meta name="theme-color" content="#ffffff"></meta>
        <link rel="manifest" href="/manifest.json"></link>
        <link rel="icon" href="/icons/Logoinventariobovino-512.png"></link>
        <link
          rel="apple-touch-icon"
          sizes="512x512"
          href="/icons/Logoinventariobovino-512.png"
        ></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
